site_name: Aero

nav:
- Home: index.md
- "AirCarrier": AirCarrier.md
- "Crew": Crew.md
- "Member": Member.md
- "Plane": Plane.md
- "Trip": Trip.md
- "Transitlangins": Transitlangins.md
- "Fly": Fly.md

theme:
name: material